# Site settings
author: Patrice Drayton
title: 
header-img: img/home-bg.png
email: draytonpatrice@marilynssecret.org
copyright_name: Patrice Drayton
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Patech-Patrice

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
